# Generated by Django 3.1.3 on 2020-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviedb", "0003_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(default="", max_length=50),
        ),
    ]
